# password url and username removed, forgot .gitignore for this, i'll just leave like this.
password=tcss562!
url=jdbc:mysql://project-database-instance-1.cfag2g8mouhn.us-east-2.rds.amazonaws.com:3306/PROJECT
driver=com.mysql.cj.jdbc.Driver
username=admin
